name: Local
values:
  - key: base_url
    value: 'http://localhost:8080/api/v2'
    enabled: true
  - key: pidge_url
    value: 'https://store.dev.pidge.in'
    enabled: true
  - key: petpooja_url
    value: 'https://qle1yy2ydc.execute-api.ap-southeast-1.amazonaws.com'
    enabled: true
  - key: pidge_auth
    value: Bearer c3Rrbjo0Ojg1MzpjOTMxMzA2MC0xODAyLTExZWYtYmM0My02MzZlYmUzZTlhNjQ=
    enabled: true
  - key: pidge_username
    value: testing_4_468_802
    enabled: true
  - key: pidge_password
    value: 1b96f00db4b866273a
    enabled: true
  - key: one_signal_url
    value: 'https://api.onesignal.com/apps'
    enabled: true
  - key: one_signal_app
    value: 6a62cd12-c720-401a-981b-88ce547d8a62
    enabled: true
  - key: api_version
    value: ''
    enabled: true
  - key: customer_access_token
    value: ''
    enabled: true
  - key: restaurant_id
    value: ''
    enabled: true
  - key: refresh_token
    value: ''
    enabled: true
  - key: restaurant_user_access_token
    value: ''
    enabled: true
  - key: restaurant_user_refresh_token
    value: ''
    enabled: true
  - key: restaurant_admin_access_token
    value: ''
    enabled: true
  - key: restaurant_admin_refresh_token
    value: ''
    enabled: true
  - key: customer_refresh_token
    value: ''
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: platform_user
    value: ''
    enabled: true
  - key: platform_admin
    value: ''
    enabled: true
  - key: platform_admin_access_token
    value: ''
    enabled: true
  - key: platform_admin_refresh_token
    value: ''
    enabled: true
